### ISSUE TITLE
ChocoPhlAn contains files that are not of the expected version

### ISSUE THREAD

**Issue by nick-youngblut** [biobakery/humann#8]
I'd like to include a README.md in the chocophlan directory in order to hold some metadata about the database. However, this produces the following error by humann3: 

```
CRITICAL ERROR: The directory provided for ChocoPhlAn contains files ( README.md ) that are not of the expected version. Please install the latest version of the database: 201901
```

Why not just have humann3 look for `*.ffn.gz` files? That is the only file type in the database, right?

**Comment by ljmciver** [comment]
Hi @nick-youngblut , Thanks for the post! We have to look for the "201901" in the chocophlan file names to make sure they are the version that will sync up with humann v3 and metaphlan v3. If you would either rename your README.md to fit this scheme or move it to a parent folder it should resolve the error.

Thanks,
Lauren

**Comment by nick-youngblut** [comment]
Don't you want to look for the specific file necessary instead of just checking that all files in that directory start with "201901"? Maybe it would be helpful to either check for the specific files (maybe with a dynamic coding of the date prefix) or at least check to make sure that the files with the proper file extensions are there. Then, the user can place any other files within that directory without issue.

**Comment by ljmciver** [comment]
Hi @nick-youngblut - There are a lot of files in the chocophlan folder (on the order of thousands) so the code double checks that all of the files are of the right version (just to make sure the user does not have some files from an older version too which would not be good for the run). Since there are so many files we would have to have a large list to check for all of them. Sorry this makes adding the readme to this folder a bit quirky. Can you add the "201901" to your readme file name and will this be okay? If not would it make sense for you to add the readme to the parent folder?

Thank you,
Lauren

**Comment by nick-youngblut** [comment]
OK, I'll add "201901" to the README, but I still don't see why the code can't just check for all files ending in "201901.ffn.gz", so then the presence of other files shouldn't matter. It's kind of odd that the code identifies any file with "201901" in the name is valid.
